fix: tell user column and q are required in nearest (#1249)
This implementation just takes advantage of the default arg handling of
Python.

Error message if you forget `column`:

```
TypeError: ScannerBuilder.nearest() missing 1 required positional argument: 'column'
```

Error message if you forget `column` and `q`:

```
TypeError: ScannerBuilder.nearest() missing 2 required positional arguments: 'column' and 'q'
```