fix: fix release versions (#2897)
Solve the issue when publishing rust
```
- cargo package -v --no-verify                            ✔
error: all dependencies must have a version specified when packaging.
dependency `lance-encoding` does not specify a version
Note: The packaged dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```
Give the java pom correct versions