test: standardize IO tests and improve assertions (#4923)
* `IOTracker` is now public in `lance-io`, so it can be re-used
throughout the codebase.
* Added new assertions `assert_io_eq!()`, `assert_io_lt!()` and
`assert_io_gt!()` which will print out the list of requests in case of
failure:

```rust
thread 'dataset::tests::test_load_manifest_iops' panicked at rust/lance/src/dataset.rs:2882:9:
assertion failed: `(left == right)`: Expected read_iops to be 3, got 2. Requests: [
    IORequest(method=list, path="test/_versions"),
    IORequest(method=get_opts, path="test/_versions/1.manifest"),
]

Diff < left / right > :
<2
>3
```