fix: add _rowid when `use_stats=False` (#1700)
When `use_stats=False`, we need to add `_rowid` to the projection if
there are additional columns we need to pull. Otherwise we get:

```
ValueError: LanceError(IO): Error during planning: TakeExec requires the input plan to have a column named '_rowid'
```