fix: set prost to minimum 0.12.2 (#2167)
this is required because we need Config `enable_type_names` method.

Fixes issue when installing python:
```
$ maturin develop

error[E0599]: no method named `enable_type_names` found for struct `Config` in the current scope
 --> /Users/albertlockett/Development/sophon/src/lance/rust/lance-encoding/build.rs:8:17
  |
8 |     prost_build.enable_type_names();
  |                 ^^^^^^^^^^^^^^^^^ method not found in `Config`
  ```