chore(deps): allow using newer version of time crate (#8296)
The `time` dependency was pinned to 0.3.47 in
https://github.com/lance-format/lance/pull/7222/commits/e090896f87a4cb692d978e9920b3b976d8a4eb10
to mitigate this build error in `aws-smithy-types`:

```console
error[E0119]: conflicting implementations of trait `From<format_description::parse::format_item::HourBase>` for type `<format_description::parse::format_item::HourBase as format_description::parse::format_item::ModifierValue>::Type`
  --> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/aws-smithy-types-1.4.5/src/timeout.rs:49:1
   |
49 | impl<T> From<T> for CanDisable<T> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `time`:
           - impl From<format_description::parse::format_item::HourBase> for <format_description::parse::format_item::HourBase as format_description::parse::format_item::ModifierValue>::Type;
```

But that blocks using `lance` in projects that require features from a
newer version of `time`. The conflict was fixed a long time ago by
https://github.com/time-rs/time/pull/786.