chore: upgrade aws-config for aarch64-pc-windows support (#2510)
Upgrades `aws-config` because `aws-config@0.56` has a dependency on
`ring@0.16` [^1] which does not support `aarch64-pc-windows` [^2].

> error: failed to run custom build command for `ring v0.16.20`.

Support for `aarch64-pc-windows` was added in `ring@0.17` [^3] which
`aws-config@0.57` uses [^4].

Unfortunately, there's a hideous amount of changes between these two
version, although no breaking changes are mentioned in the changelog
[^5]. Does a maintainer here have a suggestion of what kind of testing
we might need to do?

[^1]:
https://github.com/awslabs/aws-sdk-rust/blob/d212f8dd428e140b8ff414261f6921b2901a7dbc/sdk/aws-config/Cargo.toml#L98-L100
[^2]: https://github.com/briansmith/ring/issues/1514
[^3]:
https://github.com/briansmith/ring/issues/1167#issuecomment-1745560468
[^4]:
https://github.com/awslabs/aws-sdk-rust/blob/511abe92a476c27d1e49758fe54eac0886ecf731/sdk/aws-config/Cargo.toml#L98-L100
[^5]: https://github.com/awslabs/aws-sdk-rust/compare/d212f8d..511abe9