feat: add outer retry loop to CloudObjectReader::size (#2151)
A user was getting periodic errors from GCS:

```
OSError: Io error: Execution error: LanceError(IO): Generic GCS error: Error after 0 retries in 122.602µs, max_retries:10, retry_timeout:180s, source:error sending request for url (https://storage.googleapis.com/some-file.lance): connection error: unexpected end of file, /home/runner/work/lance/lance/rust/lance-io/src/object_reader.rs:61:12
```

This request was not retried because it was a request error (`error
sending request`) and not a connection error and it is not a timeout.
Therefore it does not meet the criteria currently defined by
`object_store`. However, this does appear to be a legitimate "this can
sometimes randomly fail" error that we want to retry.

We already had an outer retry loop in `get_range` for a similar kind of
failure and I just extended that outer retry loop to `size`.