fix: remove default memory cap for index training (#1702)
Removed hard-coded 4GB limit, as sometimes that produces errors like:

```
OSError: LanceError(IO): Resources exhausted: Failed to allocate additional 5618883160 bytes for ExternalSorter[0] with 0 bytes already allocated - maximum available is 4284481536, /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/convert/mod.rs:716:9
```

Instead users can set this as an environment variable:

```shell
export LANCE_MEMORY_LIMIT=$((4 * 1024 * 1024 * 1024))
```

I did an environment variable for now because the indexing parameters
are a mess and I don't want to refactor them yet.

Because we don't know how much memory the client machine may have, we
set it to unbounded by default.

Closes #1701