fix: escape `type` keyword in `tracing::info!` macros (#4068)
I run into issues due to the use of the `type` keyword in
`tracing::info` macros - this PR replaces it with the escaped `r#type`
version.

Sample of the error I previously got:
```
error: no rules expected keyword `type`
    --> /Users/.../.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/lance-table-0.30.0/src/io/deletion.rs:113:13
     |
113  |             info!(target: TRACE_FILE_AUDIT, mode=AUDIT_MODE_CREATE, type=AUDIT_TYPE_DELETION, path = path.to_string());
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no rules expected this token in macro call
```